ATT_APIPlatform_SampleApps/RESTFul/DC/Java/app1/src/main/java/com/att/api/dc/model/ConfigBean.java
package com.att.api.dc.model;

import java.io.IOException;
import java.io.Serializable;

import com.att.api.config.AppConfig;

public class ConfigBean implements Serializable {
    private static final long serialVersionUID = 138893983L;

    public AppConfig getConfig() throws IOException {
        return AppConfig.getInstance();
    }

    public String getLinkSource() throws IOException {
        return getConfig().getProperty("linkSource");
    }

    public String getLinkDownload() throws IOException {
        return getConfig().getProperty("linkDownload");
    }

    public String getLinkHelp() throws IOException {
        return getConfig().getProperty("linkHelp");
    }
}

ATT_APIPlatform_SampleApps/RESTFul/DC/Java/app1/src/main/java/com/att/api/dc/model/DCResponse.java
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */
package com.att.api.dc.model;

import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;

import org.json.JSONObject;

/**
 * Immutable class that holds DC API response information.
 *
 * @author <a href="mailto:pk9069@att.com">Pavel Kazakov</a>
 * @version 3.0
 * @since 2.2
 */
public final class DCResponse {

    /** Contains a map of key-value pairs for device capabilities. */
    private Map<String, String> deviceMap;

    /**
     * Disallow default constructor call outside of class.
     *
     * @since 3.0
     */
    private DCResponse() {
    }

    /**
     * Create a DC response by parsing a JSON object.
     *
     * @param jobj JSON object to parse
     * @deprecated replaced by {@link #valueOf(JSONObject)}
     */
    @Deprecated
    public DCResponse(final JSONObject jobj) {
        DCResponse response = DCResponse.valueOf(jobj);
        this.deviceMap = response.deviceMap;
    }

    /**
     * Factory method for creating a DC response by parsing a JSON object.
     *
     * @param jobj JSON object to parse
     * @return DC response
     * @since 3.0
     */
    public static DCResponse valueOf(JSONObject jobj) {
        // TODO (pk9069): this class needs to be moved to an explicit model
        // and not just a map

        DCResponse response = new DCResponse();

        // use linkedhashmap to preserve order
        response.deviceMap = new LinkedHashMap<String, String>();

        JSONObject deviceInfo = jobj.getJSONObject("DeviceInfo");
        JSONObject deviceId = deviceInfo.getJSONObject("DeviceId");
        JSONObject capabilities = deviceInfo.getJSONObject("Capabilities");
        String typeAllocationCode = deviceId.getString("TypeAllocationCode");
        response.deviceMap.put("TypeAllocationCode", typeAllocationCode);

        // suppress generics warning
        @SuppressWarnings("unchecked")
        Iterator<String> keys = capabilities.keys();
        while (keys.hasNext()) {
            String key = keys.next();
            String value = capabilities.getString(key);
            response.deviceMap.put(key, value);
        }

        return response;
    }

    /**
     * Gets a map of key-value pairs for device capabilities.
     *
     * @return map of key-value pairs.
     */
    public Map<String, String> getResponseMap() {
        // TODO (pk9069): return copy, thereby avoid exposing internals
        return deviceMap;
    }
}

ATT_APIPlatform_SampleApps/RESTFul/DC/Java/app1/src/main/java/com/att/api/dc/model/package-info.java
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */

/**
 * Provides classes for holding DC API responses.
 *
 * <p>
 * For more information, refer to the documenation at
 * <a href="https://developer.att.com/docs/apis/rest/2/Device%20Capabilities">DC</a>.
 * </p>
 *
 * @author <a href="mailto:pk9069@att.com">Pavel Kazakov</a>
 * @since 2.2
 * @see com.att.api.dc.model.DCResponse
 */
package com.att.api.dc.model;

ATT_APIPlatform_SampleApps/RESTFul/DC/Java/app1/src/main/java/com/att/api/dc/controller/DCController.java
package com.att.api.dc.controller;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.att.api.controller.APIController;
import com.att.api.oauth.OAuthToken;
import com.att.api.rest.RESTException;
import com.att.api.dc.model.ConfigBean;
import com.att.api.dc.model.DCResponse;
import com.att.api.dc.service.DCService;

import java.io.IOException;

public class DCController extends APIController {
    private static final long serialVersionUID = 1L;

    private void handleGetDeviceInfo(HttpServletRequest request,
            HttpServletResponse response, OAuthToken token) {
            
        try {
            DCService service = new DCService(appConfig.getFQDN(), token);
            DCResponse dcResponse = service.getDeviceCapabilities();

            request.setAttribute("dcResponse", dcResponse);
        } catch (RESTException e) {
            request.setAttribute("error", e.getMessage());
        }
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        OAuthToken token = null;
        try {
            final String error = (String) request.getParameter("error");
            if (error != null) {
                String errorDesc = request.getParameter("error_description");
                throw new RESTException("error=" + error 
                        + "&error_description=" + errorDesc);
            }

            token = this.getSessionToken(request, response);
            if (token == null) {
                return;
            }
            handleGetDeviceInfo(request, response, token);
        } catch (RESTException e) {
            request.setAttribute("error", e.getMessage());
        }

        final String forward = "WEB-INF/DC.jsp";
        request.setAttribute("cfg", new ConfigBean());
        RequestDispatcher dispatcher = request.getRequestDispatcher(forward);
        dispatcher.forward(request, response);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        doPost(request, response);
    }
}

ATT_APIPlatform_SampleApps/RESTFul/DC/Java/app1/src/main/webapp/WEB-INF/DC.jsp
<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:useBean id="dateutil" class="com.att.api.util.DateUtil" scope="request">
</jsp:useBean>
<!-- 
Licensed by AT&T under 'Software Development Kit Tools Agreement.' 2013
TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION: http://developer.att.com/sdk_agreement/
Copyright 2013 AT&T Intellectual Property. All rights reserved. http://developer.att.com
For more information contact developer.support@att.com
-->
<html lang="en"> 
  <head> 
    <title>AT&amp;T Sample DC Application - Get Device Capabilities Application</title>
    <meta id="viewport" name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="style/common.css">
    <script type="text/javascript">
	    var _gaq = _gaq || [];
	    _gaq.push(['_setAccount', 'UA-33466541-1']);
        _gaq.push(['_trackPageview']);

        (function () {
             var ga = document.createElement('script');
             ga.type = 'text/javascript';
             ga.async = true;
             ga.src = ('https:' == document.location.protocol ? 'https://ssl'
                                         : 'http://www')
                                         + '.google-analytics.com/ga.js';
             var s = document.getElementsByTagName('script')[0];
             s.parentNode.insertBefore(ga, s);
         })();
    </script>
  </head>
  <body>
    <div id="pageContainer">
      <div id="header">
        <div class="logo"> 
        </div>
        <div id="menuButton" class="hide">
          <a id="jump" href="#nav">Main Navigation</a>
        </div> 
        <ul class="links" id="nav">
          <li><a href="#" target="_blank">Full Page<img src="images/max.png" /></a>
          <span class="divider"> |&nbsp;</span>
          </li>
          <li>
          <a href="${cfg.linkSource}" target="_blank">Source<img src="images/opensource.png" /></a>
          <span class="divider"> |&nbsp;</span>
          </li>
          <li>
          <a href="${cfg.linkDownload}" target="_blank">Download<img src="images/download.png"></a>
          <span class="divider"> |&nbsp;</span>
          </li>
          <li>
          <a href="${cfg.linkHelp}" target="_blank">Help</a>
          </li>
          <li id="back"><a href="#top">Back to top</a>
          </li>
        </ul> <!-- end of links -->
      </div> <!-- end of header -->
      <div id="content">
        <div id="contentHeading">
          <h1>AT&amp;T Sample DC Application - Get Device Capabilities Application</h1>
          <div class="border"></div>
          <div id="introtext">
            <div><b>Server Time:&nbsp;</b><c:out value="${dateutil.serverTime}" /></div>
            <div><b>Client Time:&nbsp;</b><script>document.write("" + new Date());</script></div>
            <div><b>User Agent:&nbsp;</b><script>document.write("" + navigator.userAgent);</script></div>
          </div> <!-- end of introtext -->
        </div> <!-- end of contentHeading -->

        <!-- SAMPLE APP CONTENT STARTS HERE! -->
        <div class="formBox" id="formBox">
          <div id="formContainer" class="formContainer">
            <h2>Feature 1: Get Device Capabilities</h2>
            <div class="lightBorder"></div>

            <div class="note">
              <strong>OnNet Flow:</strong>
              Request Device Capabilities details from the AT&amp;T network
              for the mobile device of an AT&amp;T subscriber who is using an AT&amp;T direct Mobile data
              connection to access this application.
              <br />
              <strong>OffNet Flow:</strong> Where the end-user is not on an AT&amp;T Mobile data connection
              or using a Wi-Fi or tethering connection while accessing this application. This
              will result in an HTTP 400 error.
            </div> <!-- end note -->

            <c:if test="${not empty dcResponse}">
              <div class="successWide">
                <strong>SUCCESS:</strong>
                <br />
                Device parameters listed below.
              </div>
              <table class="kvp" id="kvp">
                <thead>
                  <tr>
                    <th>Parameter</th>
                    <th>Value</th>
                  </tr>
                </thead>
                <tbody>
                  <c:forEach var="entry" items="${dcResponse.responseMap}">
                    <tr>
                      <td data-value="Parameter">
                        <c:out value="${entry.key}" />
                      </td>
                      <td data-value="Value">
                        <c:out value="${entry.value}" />
                      </td>
                    </tr>
                  </c:forEach>
                </tbody>
              </table>
            </c:if>

            <c:if test="${not empty error}">
              <div class="errorWide">
                <b>ERROR:</b><br>
                <c:out value="${error}" />
              </div>
            </c:if>

          </div> <!-- end of formContainer -->
        </div> <!-- end of formBox -->
        <!-- SAMPLE APP CONTENT ENDS HERE! -->

      </div> <!-- end of content -->
      <div class="border"></div>
      <div id="footer">
        <div id="powered_by">
          Powered by AT&amp;T Cloud Architecture
        </div>
        <p>
        The Application hosted on this site are working examples
        intended to be used for reference in creating products to consume
        AT&amp;T Services and not meant to be used as part of your
        product. The data in these pages is for test purposes only and
        intended only for use as a reference in how the services perform.
        <br /><br />
        For download of tools and documentation, please go to 
        <a href="https://devconnect-api.att.com/" 
          target="_blank">https://devconnect-api.att.com</a>
        <br> For more information contact 
        <a href="mailto:developer.support@att.com">developer.support@att.com</a>
        <br /><br />
        &#169; 2013 AT&amp;T Intellectual Property. All rights reserved. 
        <a href="http://developer.att.com/" target="_blank">http://developer.att.com</a>
        </p>
      </div> <!-- end of footer -->
    </div> <!-- end of page_container -->
  </body>
</html>