ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/java/com/att/api/sms/model/ConfigBean.java
package com.att.api.sms.model;

import java.io.IOException;
import java.io.Serializable;

import com.att.api.config.AppConfig;

public class ConfigBean implements Serializable {
    private static final long serialVersionUID = 138893983L;

    public AppConfig getConfig() throws IOException {
        return AppConfig.getInstance();
    }

    public String getLinkSource() throws IOException {
        return getConfig().getProperty("linkSource");
    }

    public String getLinkDownload() throws IOException {
        return getConfig().getProperty("linkDownload");
    }

    public String getLinkHelp() throws IOException {
        return getConfig().getProperty("linkHelp");
    }

    public String getPollMsgsShortCode() throws IOException {
        return getConfig().getProperty("getMsgsShortCode");
    }

    public String getReceiveMsgsShortCode() throws IOException {
        return getConfig().getProperty("receiveMsgsShortCode");
    }
}

ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/java/com/att/api/sms/model/SMSMessage.java
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */

package com.att.api.sms.model;

/**
 * Immutable class that holds an SMS message.
 *
 * @author <a href="mailto:pk9069@att.com">Pavel Kazakov</a>
 * @version 3.0
 * @since 2.2
 */
public final class SMSMessage {

    /** Message index. */
    private final String messageIndex;

    /** Message text. */
    private final String messageText;

    /** Message address. */
    private final String messageAddress;

    /**
     * Creates an SMSMessage object.
     *
     * @param mIndex message index
     * @param mText message text
     * @param mAddr message address
     */
    public SMSMessage(final String mIndex, final String mText,
            final String mAddr) {
        this.messageIndex = mIndex;
        this.messageText = mText;
        this.messageAddress = mAddr;
    }

    /**
     * Gets message index.
     *
     * @return message index
     */
    public String getMessageIndex() {
        return this.messageIndex;
    }

    /**
     * Gets message text.
     *
     * @return message text
     */
    public String getMessageText() {
        return this.messageText;
    }

    /**
     * Gets sender address.
     *
     * @return sender address
     */
    public String getSenderAddress() {
        return this.messageAddress;
    }
}

ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/java/com/att/api/sms/model/SMSReceiveMsg.java
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */

package com.att.api.sms.model;

/**
 * Immutable class that holds SMS API receive message information.
 *
 * @author <a href="mailto:pk9069@att.com">Pavel Kazakov</a>
 * @version 3.0
 * @since 2.2
 */
public final class SMSReceiveMsg {
    /** Message date time. */
    private final String dTime;

    /** Message id. */
    private final String msgId;

    /** Message body. */
    private final String msg;

    /** Sender address. */
    private final String senderAddr;

    /** Destination address. */
    private final String destinationAddr;

    /**
     * Creates an SMSReceiveMsg object.
     *
     * @param dTime time of message
     * @param msgId message id
     * @param msg message
     * @param senderAddr sender address
     * @param destinationAddr destination address
     */
    public SMSReceiveMsg(String dTime, String msgId, String msg,
            String senderAddr, String destinationAddr) {

        // TODO (pk9069): probably not the best place to set default...
        if (msgId == null || msgId.equals("")) {
            msgId = "-";
        }

        this.dTime = dTime;
        this.msgId = msgId;
        this.msg = msg;
        this.senderAddr = senderAddr;
        this.destinationAddr = destinationAddr;
    }

    /**
     * Gets date-time of message.
     *
     * @return date time
     */
    public String getDateTime() {
        return dTime;
    }

    /**
     * Gets message id.
     *
     * @return message id
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Gets message.
     *
     * @return message
     */
    public String getMsg() {
        return msg;
    }

    /**
     * Gets address of sender.
     *
     * @return address of sender
     */
    public String getSenderAddr() {
        return senderAddr;
    }

    /**
     * Gets destination of address.
     *
     * @return destination of address.
     */
    public String getDestinationAddr() {
        return destinationAddr;
    }
}

ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/java/com/att/api/sms/model/SMSStatus.java
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */

package com.att.api.sms.model;

/**
 * Immutable class that holds SMS API status information.
 *
 * @author <a href="mailto:pk9069@att.com">Pavel Kazakov</a>
 * @version 3.0
 * @since 2.2
 */
public final class SMSStatus {
    /** SMS message id. */
    private final String msgId;

    /** Address. */
    private final String addr;

    /** Delivery status. */
    private final String deliveryStatus;

    /**
     * Creates an SMSStatus object.
     *
     * @param msgId message id
     * @param addr address
     * @param deliveryStatus delivery status
     */
    public SMSStatus(String msgId, String addr, String deliveryStatus) {
        this.msgId = msgId;
        this.addr = addr;
        this.deliveryStatus = deliveryStatus;
    }

    /**
     * Gets message id.
     *
     * @return message id.
     */
    public String getMessageId() {
        return msgId;
    }

    /**
     * Gets address.
     *
     * @return address
     */
    public String getAddress() {
        return addr;
    }

    /**
     * Gets delivery status.
     *
     * @return delivery status
     */
    public String getDeliveryStatus() {
        return deliveryStatus;
    }
}

ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/java/com/att/api/sms/model/package-info.java
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */

/**
 * Provides classes for holding SMS API responses.
 *
 * @author <a href="mailto:pk9069@att.com">Pavel Kazakov</a>
 * @since 2.2
 */

package com.att.api.sms.model;

ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/java/com/att/api/sms/controller/SMSController.java
package com.att.api.sms.controller;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.json.JSONArray;
import org.json.JSONObject;

import com.att.api.controller.APIController;
import com.att.api.oauth.OAuthToken;
import com.att.api.sms.model.ConfigBean;
import com.att.api.sms.model.SMSMessage;
import com.att.api.sms.model.SMSReceiveMsg;
import com.att.api.sms.model.SMSStatus;
import com.att.api.sms.service.SMSFileUtil;
import com.att.api.sms.service.SMSService;

import java.io.IOException;

public class SMSController extends APIController {
    private static final long serialVersionUID = 1L;

    private void handleSendSMS(final HttpServletRequest request) {
        if (request.getParameter("sendSMS") == null) {
            return;
        }

        try {
            OAuthToken token = getFileToken();
            SMSService service = new SMSService(appConfig.getFQDN(), token);

            String addr = request.getParameter("address");
            request.getSession().setAttribute("addr", addr);
            String msg = request.getParameter("message");
            boolean getNotification 
                = request.getParameter("chkGetOnlineStatus") != null;
            
            JSONObject jresponse = service.sendSMS(addr, msg, getNotification);
            JSONObject smsResponse 
                = jresponse.getJSONObject("outboundSMSResponse");
            String sendId = smsResponse.getString("messageId"); 
            request.setAttribute("sendId", sendId);

            if (!getNotification) {
                request.getSession().setAttribute("statusId", sendId);
            }
		
            request.setAttribute("statusId", sendId);
            if (smsResponse.has("resourceReference")) {
                String resourceURL = smsResponse.getJSONObject
                    ("resourceReference").getString("resourceURL");
                request.setAttribute("resourceURL", resourceURL);
            }
        } catch (Exception e) {
            request.setAttribute("sendError", e.getMessage());
        }
    }

    private void handleGetStatus(final HttpServletRequest request) {
        if (request.getParameter("getStatus") == null) {
            return;
        }

        try {
            final OAuthToken token = getFileToken();
            final String msgid = request.getParameter("messageId");
            request.getSession().setAttribute("statusId", msgid);

            SMSService service = new SMSService(appConfig.getFQDN(), token);
            JSONObject jobj = service.getSMSDeliveryStatus(msgid);
            JSONObject jInfoList = jobj.getJSONObject("DeliveryInfoList");
            JSONArray jstatuses =  jInfoList.getJSONArray("DeliveryInfo");
            SMSStatus[] statuses = new SMSStatus[jstatuses.length()];
            
            for (int i = 0; i < jstatuses.length(); ++i) {
                JSONObject jstatus = jstatuses.getJSONObject(i);
                SMSStatus status = new SMSStatus
                    (
                     jstatus.getString("Id"),
                     jstatus.getString("Address"),
                     jstatus.getString("DeliveryStatus")
                    );
                statuses[i] = status;
            }

            final String resourceURL = jInfoList.getString("ResourceUrl");

            request.setAttribute("resultGetStatuses", statuses);
            request.setAttribute("resourceURL", resourceURL);
        } catch (Exception e) {
            request.setAttribute("statusError", e.getMessage());
        }
    }

    private void handleGetMsgs(final HttpServletRequest request) {
        if (request.getParameter("getMessages") == null) {
            return;
        }

        try {
            String shortCode = appConfig.getProperty("getMsgsShortCode");
            if (shortCode == null) return;

            OAuthToken token = getFileToken();

            SMSService service = new SMSService(appConfig.getFQDN(), token);
            JSONObject jobj = service.getSMSReceive(shortCode);
            JSONObject msgList = jobj.getJSONObject("InboundSmsMessageList");

            String numbMessages = 
                msgList.getString("NumberOfMessagesInThisBatch");

            String numbPending = 
                msgList.getString("TotalNumberOfPendingMessages");

            JSONArray msgs = msgList.getJSONArray("InboundSmsMessage"); 

            SMSMessage[] smsMsgs = new SMSMessage[msgs.length()];
            for (int i = 0; i < msgs.length(); ++i) {
                final JSONObject jmsg = msgs.getJSONObject(i);
                final String msgId = jmsg.getString("MessageId");
                final String msgIndex = jmsg.getString("Message");
                final String senderAddr = jmsg.getString("SenderAddress");
                SMSMessage smsMsg = new SMSMessage(msgId, msgIndex, senderAddr);
                smsMsgs[i] = smsMsg;
            }

            request.setAttribute("SMSMessages", smsMsgs);
            request.setAttribute("numbMessages", numbMessages);
            request.setAttribute("numbPending", numbPending);
        } catch (Exception e) {
            request.setAttribute("receiveError", e.getMessage());
        }
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        handleSendSMS(request);

        handleGetStatus(request);

        handleGetMsgs(request);

        final SMSStatus[] statuses = SMSFileUtil.getStatuses();
        request.setAttribute("resultStatuses", statuses);

        final SMSReceiveMsg[] receiveMsgs = SMSFileUtil.getReceiveMsgs();
        request.setAttribute("resultReceiveMsgs", receiveMsgs);

        request.setAttribute("cfg", new ConfigBean());

        final String forward = "/WEB-INF/SMS.jsp";
        RequestDispatcher dispatcher = request.getRequestDispatcher(forward);
        dispatcher.forward(request, response);

    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        doPost(request, response);
    }
}

ATT_APIPlatform_SampleApps/RESTFul/SMS/Java/app1/src/main/webapp/WEB-INF/SMS.jsp
<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:useBean id="dateutil" class="com.att.api.util.DateUtil" scope="request">
</jsp:useBean>
<!-- 
Licensed by AT&T under 'Software Development Kit Tools Agreement.' 2013
TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION: http://developer.att.com/sdk_agreement/
Copyright 2013 AT&T Intellectual Property. All rights reserved. http://developer.att.com
For more information contact developer.support@att.com
-->
<html lang="en"> 
  <head> 
    <title>AT&amp;T Sample Application - Basic SMS Service Application</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <meta id="viewport" name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="style/common.css">
    <script src="scripts/utils.js"></script>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-33466541-1']);
        _gaq.push(['_trackPageview']);

        (function () {
             var ga = document.createElement('script');
             ga.type = 'text/javascript';
             ga.async = true;
             ga.src = ('https:' == document.location.protocol ? 'https://ssl'
                                         : 'http://www')
                                         + '.google-analytics.com/ga.js';
             var s = document.getElementsByTagName('script')[0];
             s.parentNode.insertBefore(ga, s);
         })();
    </script>
  </head>
  <body>
    <div id="pageContainer">
      <div id="header">
        <div class="logo"></div> 
        <div id="menuButton" class="hide"><a id="jump" href="#nav">Main Navigation</a></div> 
        <ul class="links" id="nav">
          <li><a href="#" target="_blank">Full Page<img alt="fullpage" src="images/max.png" /></a>
            <span class="divider"> |&nbsp;</span>
          </li>
          <li>
            <a href="${cfg.linkSource}" target="_blank" 
                id="SourceLink">Source<img alt="source" src="images/opensource.png" /></a>
            <span class="divider"> |&nbsp;</span>
          </li>
          <li>
            <a href="${cfg.linkDownload}" target="_blank"
                id="DownloadLink">Download<img alt="download" src="images/download.png"></a>
            <span class="divider"> |&nbsp;</span>
          </li>
          <li>
            <a href="${cfg.linkHelp}" target="_blank" id="HelpLink">Help</a>
          </li>
          <li id="back"><a href="#top">Back to top</a></li>
        </ul> <!-- end of links -->
      </div> <!-- end of header -->
      <div id="content">
        <div id="contentHeading">
          <h1>AT&amp;T Sample Application - Basic SMS Service Application</h1>
          <div class="border"></div>
          <div id="introtext">
            <div><b>Server Time:&nbsp;</b>${dateutil.serverTime}</div> 
            <div><b>Client Time:&nbsp;</b><script>document.write("" + new Date());</script></div>
            <div><b>User Agent:&nbsp;</b><script>document.write("" + navigator.userAgent);</script></div>
          </div> <!-- end of introtext -->
        </div> <!-- end of contentHeading -->

        <div class="formBox" id="formBox">
          <div id="formContainer" class="formContainer">
            <div class="inputFields">
              <div id="sendSMSdiv">
                <h2>Feature 1: Send SMS</h2>
                <form method="post" action="sendSMS" name="sendSMSForm" id="sendSMSForm">
                  <c:if test="${not empty addr}"> 
                  <input placeholder="Address" name="address" id="address" type="text" value="${addr}"/>
                  </c:if>
                  <c:if test="${empty addr}"> 
                  <input placeholder="Address" name="address" id="address" type="text" />
                  </c:if>
                  <label>
                    Message
                    <select name="message" id="message">
                      <option value="ATT SMS sample Message">ATT SMS sample message</option>
                    </select>
                  </label>
                  <label>
                    <input type="checkbox" name="chkGetOnlineStatus" id="chkGetOnlineStatus" value="true"
                        title="If Checked, Delivery status is sent to the listener, use feature 3 to view the status" />
                    Receive Delivery Status Notification<br>
                  </label>
                  <button type="submit" class="submit" name="sendSMS" id="sendSMS">Send SMS</button>
                </form>
                <c:if test="${not empty requestScope.sendError}">
                <div class="errorWide">
                  <strong>ERROR: </strong><br>
                  ${requestScope.sendError}
                </div>
                </c:if>
                <c:if test="${not empty requestScope.sendId}">
                <div class="successWide">
                  <strong>SUCCESS: </strong><br>
                  <strong>messageId: </strong>${requestScope.sendId}<br>
                  <c:if test="${not empty requestScope.resourceURL}">
                  <strong>resourceURL: </strong>${requestScope.resourceURL}<br>
                  </c:if>
                </div>
                </c:if>
              </div> <!-- end of sendSMS -->
              <div class="lightBorder"></div>
              <div id="getStatusdiv">
                <h2>Feature 2: Get Delivery Status</h2>
                <form method="post" action="getStatus" name="getStatusForm" id="getStatusForm">
                  <c:if test="${not empty sessionScope.statusId}">
                  <input placeholder="Message ID" name="messageId" id="messageId" type="text" 
                    value="${sessionScope.statusId}">
                  </c:if>
                  <c:if test="${empty sessionScope.statusId}">
                  <input placeholder="Message ID" name="messageId" id="messageId" type="text">
                  </c:if>
                  <button type="submit" class="submit" name="getStatus" id="getStatus">Get Status</button>
                </form>
                <c:if test="${not empty requestScope.statusError}">
                <div class="errorWide">
                  <strong>ERROR: </strong><br>
                  ${requestScope.statusError}
                </div>
                </c:if>
                <c:if test="${not empty requestScope.resultGetStatuses}">
                <div class="successWide">
                  <strong>SUCCESS: </strong><br>
                  <strong>Resource URL: </strong>${requestScope.resourceURL}<br>
                </div>
                <table>
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Address</th>
                      <th>DeliveryStatus</th>
                    </tr>
                  </thead>
                  <tbody>
                  <c:forEach var="status" items="${resultGetStatuses}">
                    <tr>
                      <td data-value="Message Id"><c:out value="${status.messageId}" /></td>
                      <td data-value="Status"><c:out value="${status.address}" /></td>
                      <td data-value="Resouce Url"><c:out value="${status.deliveryStatus}" /></td>
                    </tr>
                  </c:forEach>
                  </tbody>
                </table>
                </c:if>
              </div> <!-- end of getStatus -->
              <div class="lightBorder"></div>
              <div id="receiveStatusdiv">
                <h2>Feature 3: Receive Delivery Status</h2>
                <form method="post" action="refresh" name="refreshStatusForm" id="refreshStatusForm">
                  <button type="submit" class="submit" name="receiveStatusBtn" id="receiveStatusBtn">
                    Refresh Notifications</button>
                </form>
                <table>
                  <thead>
                    <tr>
                      <th>Message Id</th>
                      <th>Address</th>
                      <th>Delivery Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <c:forEach var="status" items="${resultStatuses}">
                      <tr>
                        <td data-value="Message Id"><c:out value="${status.messageId}" /></td>
                        <td data-value="Status"><c:out value="${status.address}" /></td>
                        <td data-value="Resouce Url"><c:out value="${status.deliveryStatus}" /></td>
                      </tr>
                    </c:forEach>
                  </tbody>
                </table>
              </div><!-- end of receiveStatus -->
              <div id="getMessages">
                <h2>Feature 4: Get Messages (${cfg.pollMsgsShortCode})</h2>
                <form method="post" action="getMessages" name="getMessagesForm" id="getMessagesForm">
                  <button type="submit" class="submit" name="getMessages" id="getMessages">Get Messages</button>
                </form>
                <c:if test="${not empty requestScope.receiveError}">
                <div class="errorWide">
                  <strong>ERROR: </strong><br>
                  ${requestScope.receiveError}
                </div>
                </c:if>
                <c:if test="${not empty requestScope.numbMessages}">
                <div class="successWide">
                  <strong>SUCCESS:</strong><br>
                  <strong>Messages in this batch: <strong>${requestScope.numbMessages}<br>
                  <strong>Messages pending: <strong>${requestScope.numbPending}<br>
                </div>
                <table>
                  <thead>
                    <tr>
                      <th>Message Index</th>
                      <th>Message Text</th>
                      <th>Sender Address</th>
                    </tr>
                  </thead>
                  <tbody>
                    <c:forEach var="msg" items="${requestScope.SMSMessages}">
                    <tr>
                      <td data-value="Message Index">${msg.messageIndex}</td>
                      <td data-value="Message Text">${msg.messageText}</td>
                      <td data-value="Sender Address">${msg.senderAddress}</td>
                    </tr>
                    </c:forEach>
                  </tbody>
                </table>
                </c:if>
              </div> <!-- end of getMessages -->
              <div class="lightBorder"></div>
              <div id="receiveMsgs">
                <h2>Feature 5: Receive Messages (${cfg.receiveMsgsShortCode})</h2>
                <form method="post" action="refresh" name="receiveMessagesForm" id="receiveMessagesForm">
                  <button type="submit" class="submit" name="receiveMessages" 
                      id="receiveMessages">Refresh Received Messages</button>
                </form>
                  <table>
                    <thead>
                      <tr>
                        <th>DateTime</th>
                        <th>Message Id</th>
                        <th>Message</th>
                        <th>Sender Address</th>
                        <th>Destination Address</th>
                      </tr>
                    </thead>
                    <tbody>
                    <c:forEach var="msg" items="${resultReceiveMsgs}">
                        <tr>
                          <td data-value="DateTime"><c:out value="${msg.dateTime}" /></td>
                          <td data-value="Message Id"><c:out value="${msg.msgId}" /></td>
                          <td data-value="Message"><c:out value="${msg.msg}" /></td>
                          <td data-value="Sender Address"><c:out value="${msg.senderAddr}" /></td>
                          <td data-value="Destination Address"><c:out value="${msg.destinationAddr}" /></td>
                        </tr>
                    </c:forEach>
                  </tbody>
                </table>
              </div> <!-- end of receiveMsgs -->
            </div> <!-- end of inputFields -->
          </div> <!-- end of formContainer -->
        </div> <!-- end of formBox -->
      </div> <!-- end of content -->
      <div class="border"></div>
      <div id="footer">
        <div id="powered_by">Powered by AT&amp;T Cloud Architecture</div>
        <p>
          The Application hosted on this site are working examples intended to be used for reference in creating 
          products to consume AT&amp;T Services and not meant to be used as part of your product. The data in 
          these pages is for test purposes only and intended only for use as a reference in how the services 
          perform. 
          <br> <br> 
          For download of tools and documentation, please go to 
          <a href="https://devconnect-api.att.com/" target="_blank">https://devconnect-api.att.com</a>
          <br> 
          For more information contact 
          <a href="mailto:developer.support@att.com">developer.support@att.com</a>
          <br> <br>
          &copy; 2013 AT&amp;T Intellectual Property. All rights reserved.
          <a href="http://developer.att.com/" target="_blank">http://developer.att.com</a>
        </p>
      </div> <!-- end of footer -->
    </div> <!-- end of page_container -->
    <script>setup();</script>
  </body>
</html>